version: '3'

services:
  app:
    container_name: app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    expose:
      - '8080'
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8
    env_file:
      - .env
    ports:
      - '3306:3306'

  phpmyadmin:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "800:80"
    links:
      - mysql
    env_file:
      - .env